version: "3.2"

services:
  django:
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    build:
      context: "."
      dockerfile: "./django.dockerfile"
    ports:
      - "8000:8000"
    volumes:
      - ./app:/opt/app
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - main

  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password_user
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - main

networks:
  main:
    driver: "bridge"